{
  "hash": "512d98f7dde15874742ffa7b4e94c337",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"6: Bayesian decision analysis and practical significance with ROPE, emmeans, and marginaleffects\"\nsubtitle: \"Bayesian Mixed Effects Models with brms for Linguists\"\ndate: today\nauthor: \"Job Schepens\"\nformat: \n  html:\n    toc: true\n    toc-depth: 5\n    toc-expand: 5\n    number-sections: true\n    code-fold: true\n    code-summary: \"Show code\"\n    keep-md: true\n    embed-resources: false\n    link-external-newwindow: true\n    link-external-icon: true\n    theme:\n      light: flatly\n      dark: darkly\n  pdf:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    colorlinks: true\n    documentclass: article\n    fontsize: 11pt\n    geometry: \"top=1in,bottom=1in,left=0.75in,right=0.75in\"\n    echo: false\n    keep-md: false\nexecute:\n  freeze: auto\n  cache: true\n  warning: false\n  message: false\n---\n\n# The Problem: Does Effect X Matter?\n\n## Research Scenario\n\nImagine you've run a psycholinguistic experiment and fitted a Bayesian model. You have posterior distributions for your effects. Now you face the question:\n\n**\"Is this effect meaningful in practice?\"**\n\n- You have an estimate (e.g., β = 0.12 log-RT units)\n- You have uncertainty (95% CI: [0.08, 0.16])\n- But: Is this difference big enough to matter?\n\n**Practical significance** is different from **statistical significance**:\n\n- Statistical: \"Is there an effect?\" (distinguishable from noise) (we will discuss this in the session on Bayes Factor)\n- Practical: \"Does it matter?\" (large enough to care about)\n\n## Why Practical Significance Matters\n\nConsider these scenarios:\n\n**Scenario A: Statistically credible but trivial**\n\n- Effect: 2ms difference in reading time\n- 95% CI: [1ms, 3ms] (clearly non-zero!)\n- But: Readers can't perceive < 20ms differences\n- **Conclusion**: Real effect, but irrelevant\n\n**Scenario B: Uncertain but possibly large**\n\n- Effect: 50ms difference (noticeable to readers)\n- 95% CI: [-10ms, 110ms] (wide uncertainty)\n- Traditional conclusion: \"not significant\"\n- But: Most credible values are meaningful\n- **Conclusion**: Worth investigating further\n\n\n\n# Where We Are in the Analysis Workflow\n\n## The Bayesian Workflow So Far\n\nLet's review where we've been:\n\n1. **Module 01**: Set priors\n2. **Module 02**: Prior predictive checks \n3. **Module 03**: Posterior predictive checks\n4. **Module 04**: Compare priors → Sensitivity analysis\n5. **Module 05**: Compare models → Evaluate predictive performance (LOO)\n6. **Today (Module 06)**: Practical significance (ROPE + comparisons)\n7. **Module 07**: Bayes factors & hypothesis comparison\n8. **Module 08**: Convergence \n\n## When to Use Each Approach\n\n```\n┌─────────────────────────────────────────────────────────────┐\n│  QUESTION                          │  TOOL                  │\n├─────────────────────────────────────────────────────────────┤\n│  Which model structure is better?  │  LOO (Module 05)       │\n│  Is effect meaningful?             │  ROPE (Module 06)      │\n│  Compare multiple groups?          │  emmeans (Module 06)   │\n│  Custom predictions/contrasts?     │  marginaleffects (M06) │\n│  Evidence for hypothesis?          │  Bayes Factor (M07)    │\n│  Are estimates robust to priors?   │  Prior comparison (M04)│\n└─────────────────────────────────────────────────────────────┘\n```\n\n## Choosing The Right Tool\n\n**Use ROPE when:**\n\n- You want to declare \"effect too small to matter\"\n- You need clear decision rules (accept/reject/undecided)\n\n**Use emmeans when:**\n\n- You have factorial designs (multiple groups/conditions)\n\n**Use marginaleffects when:**\n\n- You're working with complex models (GAMs, interactions)\n\n**Use Bayes Factors (Module 07) when:**\n\n- You want to quantify evidence for one hypothesis over another (see Module 07)\n\n**Use LOO (Module 05) when:**\n\n- Comparing different model structures\n- Doing feature selection\n- Predictive performance is primary concern\n\n## Setup\n\n\n::: {.cell}\n\n:::\n\n\n## Generate Reaction Time Data\n\nWe'll generate RT data similar to previous modules, but with specific properties useful for hypothesis testing demonstrations:\n\n- Clear directional effect (Condition B slower than A)\n- Effect size in a realistic range for psycholinguistics\n- Adequate sample size for stable estimates\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 6\n  condition     n mean_rt median_rt sd_rt mean_log_rt\n  <fct>     <int>   <dbl>     <dbl> <dbl>       <dbl>\n1 A           720     410       395   114        5.98\n2 B           720     459       439   133        6.09\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 2\n  Measure                 Value\n  <chr>                   <dbl>\n1 Effect size (log scale) 0.111\n```\n\n\n:::\n:::\n\n\n## Visualize the Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/visualize-data-1.pdf)\n:::\n:::\n\n\n## Fit the Model\n\n\n::: {.cell}\n\n:::\n\n\n## Model Summary\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` r\n Family: gaussian \n  Links: mu = identity \nFormula: log_rt ~ condition + (1 + condition | subject) + (1 | item) \n   Data: rt_data (Number of observations: 1440) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nMultilevel Hyperparameters:\n~item (Number of levels: 24) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)     0.11      0.02     0.08     0.15 1.00      965     1722\n\n~subject (Number of levels: 30) \n                          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nsd(Intercept)                 0.17      0.02     0.13     0.22 1.00      828\nsd(conditionB)                0.06      0.02     0.02     0.09 1.00      797\ncor(Intercept,conditionB)     0.04      0.26    -0.45     0.55 1.00     2292\n                          Tail_ESS\nsd(Intercept)                 1621\nsd(conditionB)                 423\ncor(Intercept,conditionB)     2137\n\nRegression Coefficients:\n           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      5.98      0.04     5.90     6.05 1.01      568      802\nconditionB     0.11      0.01     0.08     0.14 1.00     2387     2584\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.20      0.00     0.19     0.21 1.00     4298     2793\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n# ROPE (Kruschke, 2015) and Decision Analysis (Gelman et al., 2013)\n\n## ROPE\n\nStatistical significance tells us if an effect differs from zero. But:\n\n- **Statistical question:** Is the effect *exactly* zero?\n- **Practical question:** Is the effect *close enough* to zero to ignore?\n\nThis is where **ROPE** (Region of Practical Equivalence) comes in.\n\n### Making ROPE-based Decisions \n\nInstead of testing if β = 0 exactly, we define a small interval around zero:\n\n$$\\text{ROPE} = [-\\varepsilon, +\\varepsilon]$$\n\nwhere $\\varepsilon$ is the **smallest effect size we care about** (domain-specific).\n\n**Decision rules:**\n\n1. **95% HDI entirely inside ROPE** → Accept practical equivalence (effect negligible)\n2. **95% HDI entirely outside ROPE** → Reject equivalence (effect matters)  \n3. **95% HDI overlaps ROPE** → Uncertain (collect more data or accept uncertainty)\n\n::: {.callout-note}\n## Terminology: HDI vs. HPD\n\nThroughout this document, we use **HDI** (Highest Density Interval) to refer to the credible interval containing the 95% most probable parameter values with the shortest width. This is also called **HPD** (Highest Posterior Density) or **HPDI** in some literature.\n\n**All three terms refer to the same concept:**\n- HDI = Highest Density Interval (most common in modern usage)\n- HPD = Highest Posterior Density (common in older literature)  \n- HPDI = Highest Posterior Density Interval (explicit combination)\n\nThe R package `HDInterval::hdi()` and the emmeans output column `lower.HPD`/`upper.HPD` both compute this same interval type.\n:::\n\n### Setting ROPE Boundaries\n\n::: {.callout-important}\n## Common Pitfall: Post-Hoc ROPE Boundaries\n\nROPE boundaries must be set **before seeing results** based on:\n\n- Domain knowledge (e.g., \"RT differences < 50ms are imperceptible\")\n- Standardized effect sizes (e.g., \"Cohen's d < 0.1 considered negligible\")\n\n**Mistake:** Setting ROPE after looking at posterior to get desired conclusion.\n\n**Why it matters:** Post-hoc boundaries invalidate the test (like p-hacking).\n:::\n\n### Four Methods for Justifying ROPE Boundaries\n\n**From Kruschke (2015, Chapter 12):** ROPE boundaries should represent the smallest effect you care about. Here are four principled methods for setting them:\n\n#### Method 1: Previous Research / Meta-Analysis\n\nUse effect sizes from prior literature to calibrate what counts as \"small.\"\n\n\n::: {.cell}\n\n:::\n\n\n| Method | Typical Effect | ROPE Boundaries | Interpretation |\n|--------|---------------|-----------------|----------------|\n| Based on Meta-Analysis | 0.10 log-units (100ms or 10%) | [-0.03, 0.03] | Effects < 3% are small relative to field norms |\n\n\n::: {.cell}\n\n:::\n\n\n**When to use:**\n\n- Mature research area with existing effect size estimates\n- You want to compare to \"typical\" effects in the field\n- You have access to meta-analyses or large-scale studies\n\n**Example:**\n```\nIn their meta-analysis of 50 reading time studies, Smith et al. (2020) \nreport a mean effect of d = 0.35 for syntactic complexity manipulations. \nWe set our ROPE at d = 0.10 (approximately 1/3 of the typical effect), \ncorresponding to ±0.03 log-RT units.\n```\n\n#### Method 2: Measurement Precision\n\nROPE should exceed measurement error—otherwise you're testing noise.\n\n\n::: {.cell}\n\n:::\n\n\n| Method | Measurement Error | ROPE Boundaries | Interpretation |\n|--------|------------------|-----------------|----------------|\n| Based on Measurement Precision | 0.02 log-units (≈20ms) | [-0.03, 0.03] | Effects smaller than measurement error are unreliable |\n\n\n::: {.cell}\n\n:::\n\n\n**When to use:**\n\n- You have reliability/measurement error estimates\n- You want to avoid claiming effects smaller than noise\n- Measurement precision is the limiting factor\n\n**How to estimate measurement error:**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 2\n  Measure            Value          \n  <chr>              <chr>          \n1 Within-subject SD  0.085          \n2 Suggested ROPE (±) 0.127          \n3 ROPE Boundaries    [-0.127, 0.127]\n```\n\n\n:::\n:::\n\n\n#### Method 3: Perceptual/Practical Thresholds\n\nEffects below perception or practical impact are negligible by definition.\n\n\n::: {.cell}\n\n:::\n\n\n| Method | Perceptual Threshold | ROPE Boundaries | Interpretation |\n|--------|---------------------|-----------------|----------------|\n| Based on Perceptual Threshold | 50ms (0.05 log-units) | [-0.05, 0.05] | Effects imperceptible to readers are negligible |\n\n\n::: {.cell}\n\n:::\n\n\n**When to use:**\n\n- You can measure perceptual/practical thresholds\n- You care about real-world impact (not just statistical detection)\n- You have pilot data or existing benchmarks\n\n**Example applications:**\n\n- **Reading:** Just-noticeable difference in reading time\n- **Accuracy:** Minimal detectable accuracy change\n- **Rating scales:** Smallest perceived difference on Likert scale\n- **Medical:** Minimum clinically meaningful difference (MCID)\n\n**How to measure perceptual thresholds:**\n```\nPilot study design:\n1. Show participants trials from both conditions\n2. Ask: \"Did you notice any difference in difficulty/speed?\"\n3. Correlate subjective reports with actual RT differences\n4. Find threshold below which participants don't notice\n→ Use this threshold as ROPE\n```\n\n#### Method 4: Standardized Effect Sizes (Cohen's d)\n\nUse conventional effect size benchmarks from your field.\n\n**Approach:** Cohen's guidelines suggest d = 0.2 is a \"small\" effect. We'll set ROPE at half of that: d = 0.10, representing a \"very small\" effect.\n\nTo convert Cohen's d to the log-RT scale, we use:\n\n$$d = \\frac{\\mu_1 - \\mu_2}{\\text{SD}_{\\text{pooled}}}$$\n\n**Formula for pooled standard deviation:**\n\n$$\\text{SD}_{\\text{pooled}} = \\sqrt{\\frac{\\sum_{i=1}^{k} (n_i - 1) \\times \\text{SD}_i^2}{\\sum_{i=1}^{k} (n_i - 1)}}$$\n\nwhere $k$ is the number of groups (conditions), $n_i$ is the sample size for group $i$, and $\\text{SD}_i$ is the standard deviation for group $i$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Cohen's d Threshold | Pooled SD (log-units) | ROPE Lower | ROPE Upper |             Interpretation             |\n|:-------------------:|:---------------------:|:----------:|:----------:|:--------------------------------------:|\n|         0.1         |         0.278         |   -0.028   |   0.028    | Effects with d < 0.10 are 'very small' |\n\n\n:::\n:::\n\n\n**When to use:**\n\n- No domain-specific benchmarks available\n- You want to follow field conventions\n- Standardized metrics are expected in your area\n\n**Common benchmarks:**\n\n- **Cohen's d:** Small = 0.2, Medium = 0.5, Large = 0.8\n- **Correlation (r):** Small = 0.1, Medium = 0.3, Large = 0.5  \n- **R²:** Small = 0.01, Medium = 0.09, Large = 0.25\n\n**Note:** These are **conventions**, not laws of nature! Domain-specific thresholds (Methods 1-3) are usually better.\n\n\n\n### For RT Data (log-scale)\n\nFor our analysis:\n\n- **ROPE = [-0.05, +0.05]** on the log scale\n- **On original scale:** This corresponds to RT ratios between 0.95 and 1.05\n  - Since we model log(RT), a difference of ±0.05 on the log scale = $e^{\\pm 0.05}$ = multiplying RT by 0.95 to 1.05\n  - Example: If Condition A = 400ms, ROPE means effects between 380ms and 420ms (±5%)\n- **Interpretation:** RT differences smaller than 5% are too small to be practically meaningful\n\n## Understanding ROPE Graphically \n\n### Excursion to Decision Analysis: The Implicit Utility Function (Gelman et al., 2013)\n\nLet's make explicit what ROPE boundaries mean in decision-theoretic terms (Gelman et al., 2013, Chapter 9; [Stan User's Guide on Decision Analysis](https://mc-stan.org/docs/stan-users-guide/decision-analysis.html)).\n\nFollowing the formal framework of Bayesian decision analysis:\n\n#### **Step 1: Define Decisions and Outcomes**\n\n$$\n\\begin{aligned}\nD &= \\{\\text{claim meaningful}, \\text{claim negligible}, \\text{undecided}\\} \\\\\nX &= \\mathbb{R} \\quad \\text{(true effect size } \\beta \\text{)}\n\\end{aligned}\n$$\n\n- **Decisions**: We must choose one of three actions:\n\n  - Claim the effect is **meaningful** (reject practical equivalence)\n  - Claim the effect is **negligible** (accept practical equivalence)\n  - Remain **undecided** (collect more data)\n- **Outcomes**: The true but unknown effect size $\\beta$ (e.g., difference in log RT)\n\n#### **Step 2: Define Probability Distribution of Outcomes**\n\n$$\np(\\beta \\mid d, \\text{data}) = \\int p(\\beta \\mid \\theta) \\cdot p(\\theta \\mid \\text{data}) \\, d\\theta\n$$\n\n- This is our **posterior distribution** from the Bayesian model\n- Represents uncertainty about the true effect size $\\beta$ given observed data\n- The posterior is independent of our decision $d$ (decisions don't change reality!)\n\n#### **Step 3: Define Utility Function**\n\n$$\nU(\\beta, d) = \\begin{cases}\n|\\beta| & \\text{if } d = \\text{claim meaningful and } |\\beta| > \\text{ROPE} \\\\\n-2|\\beta| - 0.3 & \\text{if } d = \\text{claim meaningful and } |\\beta| \\leq \\text{ROPE (false positive)} \\\\\n1 - |\\beta| & \\text{if } d = \\text{claim negligible and } |\\beta| \\leq \\text{ROPE} \\\\\n-1.5|\\beta| - 0.3 & \\text{if } d = \\text{claim negligible and } |\\beta| > \\text{ROPE (false negative)} \\\\\n-0.15 & \\text{if } d = \\text{undecided (cost of data collection)}\n\\end{cases}\n$$\n\n**Utility interpretation:**\n\n- **Correct decisions** have positive utility that depends on effect magnitude\n- **Incorrect decisions** incur loss: fixed penalty (-0.3) + proportional penalty\n- **False positives** penalized more (-2×) than false negatives (-1.5×)\n- **Remaining undecided** has fixed cost (-0.15) representing study time, participant recruitment, delayed publication\n\n#### **Step 4: Choose Decision with Highest Expected Utility**\n\n$$\nd^* = \\arg\\max_d \\mathbb{E}[U(\\beta, d) \\mid \\text{data}] = \\arg\\max_d \\int U(\\beta, d) \\cdot p(\\beta \\mid \\text{data}) \\, d\\beta\n$$\n\nThe **Bayes optimal decision** maximizes expected utility by integrating utility over the posterior:\n\n```\nFor each decision d:\n  Expected_Utility(d) = ∫ U(β, d) × p(β | data) dβ\n  \nChoose d* with max Expected_Utility\n```\n\n**In practice:**\n\n- **Scenario 1** (posterior outside ROPE): $\\mathbb{E}[U \\mid \\text{claim meaningful}]$ is highest\n- **Scenario 2** (posterior spans ROPE): $\\mathbb{E}[U \\mid \\text{undecided}]$ is highest (uncertainty cost > data cost)\n- **Scenario 3** (posterior inside ROPE): $\\mathbb{E}[U \\mid \\text{claim negligible}]$ is highest\n\n**Scenario**: You must decide whether to claim \"Condition B is meaningfully slower\" or \"Condition B is essentially equivalent to A\".\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/utility-function-example-1.pdf)\n:::\n:::\n\n\n**What these three scenarios show:**\n\n1. **Scenario 1 (Clear Effect)**: Posterior mostly outside ROPE\n   - Most purple area falls where green line is highest\n   - **Optimal decision**: Claim meaningful effect\n   - High expected utility for \"claim meaningful\"\n\n2. **Scenario 2 (High Uncertainty)**: Posterior spans ROPE boundaries\n   - Purple area spreads across both inside and outside ROPE\n   - Risk of being wrong is high for either claim\n   - **Optimal decision**: Undecided (collect more data)\n   - Expected utility of claims reduced by uncertainty; -0.15 cost of more data is worth it\n\n3. **Scenario 3 (Negligible Effect)**: Posterior concentrated inside ROPE near zero\n   - Most purple area falls where orange line is highest\n   - **Optimal decision**: Claim negligible effect\n   - High expected utility for \"claim negligible\"\n\n**Key insight**: The optimal decision emerges from integrating the utility curves (colored lines) over the posterior (purple distribution). Where your posterior mass concentrates determines which decision maximizes expected utility.\n\n::: {.callout-note collapse=\"true\"}\n## Understanding the utility curves\n\nThe three colored lines represent different utility functions $U(\\beta, d)$ for each decision $d \\in D$. Here's how to interpret them:\n\n#### **Why different maximum values?**\n\nThe utility functions reflect different research goals:\n\n- **Orange line** ($d =$ claim_negligible): $U(\\beta, \\text{negligible}) = 1 - |\\beta|$ when $|\\beta| \\leq \\text{ROPE}$\n  * Maximum = 1.0 when $\\beta = 0$ exactly (confirming true null is maximally valuable)\n  * Decreases linearly as $\\beta$ approaches ROPE boundary\n  * **Interpretation**: \"Establishing equivalence is valuable, but less so as effect approaches practical significance threshold\"\n  \n- **Green line** ($d =$ claim_meaningful): $U(\\beta, \\text{meaningful}) = |\\beta|$ when $|\\beta| > \\text{ROPE}$  \n  * Utility equals effect size itself (no upper bound)\n  * Example: At $\\beta = 0.12$, utility = 0.12; at $\\beta = 0.25$, utility = 0.25\n  * **Interpretation**: \"Discovering larger effects has greater scientific value (stronger evidence, bigger practical impact)\"\n\n- **Gray line** ($d =$ undecided): $U(\\beta, \\text{undecided}) = -0.15$ (constant)\n  * Fixed cost independent of true $\\beta$\n  * Represents: study time, participant recruitment, delayed publication\n\n**Note**: This asymmetry is a **modeling choice** reflecting common research values. You can define different utilities based on your domain.\n\n\n#### **Why are there different penalties for incorrect decisions?**\n\nAt $\\beta = \\pm 0.05$ exactly (the ROPE boundary):\n\n$$\n\\begin{aligned}\nU(0.05, \\text{meaningful}) &= -2(0.05) - 0.3 = -0.40 \\quad \\text{(false positive: heavy penalty)} \\\\\nU(0.05, \\text{negligible}) &= -1.5(0.05) - 0.3 = -0.375 \\quad \\text{(false negative: moderate penalty)} \\\\\nU(0.05, \\text{undecided}) &= -0.15 \\quad \\text{(cost of data collection)}\n\\end{aligned}\n$$\n\nBoth wrong decisions incur:\n\n- **Fixed penalty** (-0.3): Cost of misleading the literature, wasted resources, incorrect theory\n- **Proportional penalty**: More wrong = worse (scaled by distance from truth)\n\n**Asymmetric loss structure**: False positives penalized more heavily (-2×) than false negatives (-1.5×), reflecting greater harm from claiming non-existent effects.\n\n#### **When is \"undecided\" optimal?**\n\n**KEY INSIGHT**: The plot shows utility if true $\\beta$ were known, but we have **uncertainty** (posterior distribution).\n\nThe optimal decision maximizes **expected utility**:\n\n$$\nd^* = \\arg\\max_d \\mathbb{E}[U(\\beta, d) \\mid \\text{data}] = \\arg\\max_d \\int U(\\beta, d) \\cdot p(\\beta \\mid \\text{data}) \\, d\\beta\n$$\n\n- **Low uncertainty, posterior inside ROPE**: $\\mathbb{E}[U(\\text{negligible})]$ highest\n- **Low uncertainty, posterior outside ROPE**: $\\mathbb{E}[U(\\text{meaningful})]$ highest\n- **High uncertainty spanning boundaries**: $\\mathbb{E}[U(\\text{undecided})]$ can be highest\n\n**Example**: If your 95% HDI = [-0.02, 0.08]:\n\n- Posterior mass inside ROPE → favors \"negligible\"\n- Posterior mass outside ROPE → favors \"meaningful\"\n- Risk of being wrong for either claim is high\n- Expected utility of both claims reduced by uncertainty\n- Fixed cost of \"undecided\" (-0.15) may beat both risky claims\n\nThe gray line isn't highest at any single $\\beta$ value, but wins when **averaging across uncertain $\\beta$ values weighted by posterior probability**.\n\n\n#### **Why does Utility grow with distance from boundaries**\n\n- **Larger true effects** → Higher utility for correct \"meaningful\" claim (green increases)\n- **Effects closer to zero** → Higher utility for correct \"negligible\" claim (orange increases toward 1)\n- **Being wrong by more** → Larger proportional loss (steeper slopes in penalty regions)\n\nThis encourages decisive conclusions when data strongly favor one region, but caution when near boundaries.\n:::\n\n::: {.callout-important}\n## ROPE Boundaries = Utility Crossover Points\n\nYour ROPE boundaries should be set where the utilities of \"claim meaningful\" and \"claim negligible\" are equal. This is your **smallest effect size of interest (SESOI)**: the threshold where scientific conclusions qualitatively change.\n\nIn formal decision theory terms: ROPE defines the partition of outcome space $X$ where different decisions $d \\in D$ have maximal utility.\n:::\n\n**Computing expected utilities:**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n          decision expected_utility\n1 claim_meaningful        0.1114245\n2        undecided       -0.1500000\n3 claim_negligible       -0.4671367\n```\n\n\n:::\n:::\n\n\nThe optimal decision is to **claim_meaningful** (maximizes expected utility).\n\n::: {.callout-note}\n## From Decision Theory to ROPE\n\nThe traditional ROPE decision rule:\n- \"If 95% HDI excludes ROPE → Reject null\"\n\n...is actually an approximation to:\n- \"Choose the decision with maximum expected utility\"\n\nThe HDI-based rule works well when:\n\n1. Losses are approximately symmetric\n2. We want to control error rates at ~5%\n3. We prefer simple rules over computing expected utilities\n\nFor asymmetric losses or complex decisions, computing expected utilities explicitly (as shown above) provides more principled decisions.\n:::\n\n::: {.callout-important}\n## Why ROPE Boundaries Matter\n\nROPE is not arbitrary! It's the Bayesian optimal decision given:\n\n1. Your posterior beliefs (from the model)\n2. Your utility function (encoded in ROPE boundaries)\n3. Your decision threshold (e.g., 95% credibility)\n\n**Changing ROPE boundaries = changing your utility function** = changing what you consider \"meaningful enough to matter\".\n:::\n\n### The Same Graph But Simpler\n\nROPE analysis has **three possible outcomes**, not just two as in NHST!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/three-outcome-rope-1.pdf)\n:::\n:::\n\n\n::: {.callout-important}\n## Three Outcomes, Not Two!\n\n**Current practice shows:**\n\n1. **HDI excludes ROPE** → Reject H₀ (effect is meaningful)\n   - Example: 95% HDI = [0.09, 0.15], ROPE = [−0.05, 0.05]\n   - Interpretation: \"Effect is decisively larger than our practical significance threshold\"\n\n2. **HDI inside ROPE** → Accept H₀ (effect is negligible)\n   - Example: 95% HDI = [0.01, 0.03], ROPE = [−0.05, 0.05]\n   - Interpretation: \"Effect is decisively smaller than our practical significance threshold\"\n\n3. **HDI overlaps ROPE** → UNDECIDED (insufficient precision)\n   - Example: 95% HDI = [0.03, 0.09], ROPE = [−0.05, 0.05]\n   - Interpretation: \"We cannot make a clear decision—some credible values are meaningful, others aren't\"\n   - **This is not a failure!** It's honest reporting of uncertainty\n\n:::\n\n::: {.callout-note}\n## \"Undecided\" Is a Feature, Not a Bug\n\nFrom Kruschke (2015, p. 338):\n\n> \"Be clear that any discrete decision about rejecting or accepting a null value does not exhaustively capture our knowledge about the parameter value. Our knowledge about the parameter value is described by the **full posterior distribution**.\"\n\n**When HDI overlaps ROPE:**\n- You have learned something: The effect might or might not be meaningful\n- Your options:\n  1. Collect more data to narrow the posterior\n  2. Accept the uncertainty and make a practical decision based on other factors\n  3. Use a less conservative threshold (e.g., 89% HDI instead of 95%)\n- **Don't** force a binary decision when the data don't support one!\n:::\n\n### ROPE Decision Flowchart\n\n```\n                    Calculate 95% HDI\n                            ↓\n              ┌─────────────┴─────────────┐\n              │                           │\n        Does HDI exclude ROPE?      Does HDI fall\n              │                      inside ROPE?\n              │                           │\n         YES  ↓  NO                  YES  ↓  NO\n              │                           │\n   ┌──────────┘                           └──────────┐\n   │                                                  │\n   ↓                                                  ↓\nReject H₀:                                      UNDECIDED:\n\"Effect is                                    \"Overlapping—\n meaningful\"                                   insufficient\n                                               precision\"\n                     ↑\n                     │\n                 Accept H₀:\n                \"Effect is\n                 negligible\"\n```\n\n::: {.callout-note collapse=\"true\"}\n## Manual ROPE Calculation (HDI-Based Approximation)\n\nROPE is simpler than computing utilities explicitly and works well for most research questions.\n\n**In practice, we usually use the HDI-based ROPE approximation** rather than computing expected utilities explicitly. This is computationally simpler and works well when:\n\n- Losses are approximately symmetric (false positive ≈ false negative)\n- We want standard 95% decision threshold  \n- We prefer simple rules over custom utility functions\n\nNow let's use the traditional ROPE decision rules (which approximate the decision-theoretic framework):\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 x 2\n  Measure         Value         \n  <chr>           <chr>         \n1 ROPE boundaries [-0.05, 0.05] \n2 95% HDI         [0.084, 0.142]\n3 % Below ROPE    0.0%          \n4 % Inside ROPE   0.0%          \n5 % Above ROPE    100.0%        \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"**REJECT equivalence**: Effect is practically meaningful (positive) - 95% HDI entirely above ROPE\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Decision Rule = Maximizing Expected Utility\n\n**What just happened in decision-theoretic terms:**\n\n1. **We computed posterior probabilities**: P(β in each region | Data)\n2. **We applied a decision rule**: Based on where 95% HDI falls\n3. **This approximates**: Choosing decision with maximum expected utility\n\n**The connection:**\n- When 95% HDI > ROPE: E[U(\"meaningful\")] > E[U(\"negligible\")] with high confidence\n- When 95% HDI < ROPE: E[U(\"negligible\")] > E[U(\"meaningful\")] with high confidence\n- When overlapping: Expected utilities too close to call → \"undecided\" optimal\n\n**The 95% threshold** encodes a loss function where:\n- We're willing to accept 5% risk of wrong decision\n- Losses are approximately symmetric for false positives vs. false negatives\n\nIf your losses are **asymmetric** (e.g., false positives much worse), you should:\n- Use stricter threshold (e.g., 99% HDI), OR\n- Compute expected utilities explicitly (as shown in previous section)\n:::\n\n### Visualizing ROPE\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/rope-visualization-1.pdf)\n:::\n:::\n\n:::\n\n## Warning\n\n### Three Checks Before Trusting ROPE (Note: Just Informal Best Practice Checks)\n\nBefore trusting ROPE conclusions when accepting H₀, verify precision and reliability with these three checks:\n\n**1. HDI Width: Is your estimate precise enough?**\n\n   - **Rule**: HDI width should be < half the ROPE width\n   - **Rationale**: If HDI is wide relative to ROPE, you lack precision to confidently say effect is negligible\n   - **Example**: ROPE = [-0.05, 0.05] (width 0.10) → HDI width should be < 0.05\n   - **Measures**: Overall precision of your estimate\n   - **If fail**: Collect more data before claiming negligible effect\n   - **Source**: Kruschke (2018, 2015), Lakens (2018)\n\n**2. Effective Sample Size (ESS): Is your posterior reliable?**\n\n   - **Rule**: ESS bulk > 1000 AND ESS tail > 1000\n   - **Rationale**: Low ESS means MCMC chains haven't converged well - posterior estimates unreliable\n   - **ESS bulk**: Measures sampling efficiency for central posterior\n   - **ESS tail**: Measures sampling efficiency for HDI boundaries (critical for ROPE!)\n   - **Measures**: Quality of MCMC sampling, not data quantity\n   - **If fail**: Increase MCMC iterations, check convergence diagnostics (R̂), consider reparameterization\n   - **Source**: e.g.: Vehtari et al. (2021) \"Rank-Normalization, Folding, and Localization: An Improved R̂ for Assessing Convergence of MCMC\"; Stan Development Team documentation on MCMC diagnostics\n\n**3. HDI Position: Is the effect centered near zero? (ONLY when accepting H₀)**\n\n   - **Rule**: HDI midpoint should be close to zero (e.g., within inner 50% of ROPE)\n   - **Rationale**: HDI inside ROPE but far from zero suggests bias or one-sided effect\n   - **Example**: ROPE = [-0.05, 0.05], HDI = [0.03, 0.045] → midpoint = 0.0375 (close to boundary, suspicious!)\n   - **Better example**: HDI = [-0.01, 0.02] → midpoint = 0.005 (centered near zero, reassuring)\n   - **Measures**: Location of effect, not just precision\n   - **Applies to**: ONLY when accepting H₀ (claiming negligible effect); skip this check when rejecting H₀\n   - **If fail**: Re-examine priors, check for model misspecification, or acknowledge effect may be small but non-zero\n   - **Source**: Practical heuristic not explicitly stated in literature, but follows from Kruschke's (2018, p. 275) emphasis that accepting null requires \"the estimated value be compatible with the null value\" - an HDI asymmetrically positioned near a ROPE boundary questions this compatibility\n\n::: {.callout-tip}\n## Why these three checks?\n\n- **Check 1 (HDI width)**: Ensures sufficient **precision** - can you distinguish effect from zero? (Kruschke, 2018) - *Always needed*\n- **Check 2 (ESS)**: Ensures **reliability** - are the posterior estimates trustworthy? (Vehtari et al., 2021) - *Always needed*\n- **Check 3 (HDI position)**: Ensures **centrality** - is the effect truly centered near zero, or just barely inside ROPE? (Practical heuristic derived from Kruschke's compatibility principle) - *Only for accepting H₀*\n\nAll three can pass even with small sample size if the effect is truly negligible and model converges well. All three can fail with large sample size if MCMC struggles or effect is near boundary.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 x 2\n  Check                             Value                                       \n  <chr>                             <chr>                                       \n1 \"1. HDI Width\"                    0.0576                                      \n2 \"   Status\"                       ✗ FAIL (> 0.05) - Need more data            \n3 \"2. Effective Sample Size (bulk)\" 2387                                        \n4 \"   Effective Sample Size (tail)\" 2584                                        \n5 \"   Status\"                       ✓ PASS (> 1000)                             \n6 \"3. HDI Position (midpoint)\"      0.1132                                      \n7 \"   Distance from zero\"           0.1132                                      \n8 \"   Status\"                       N/A (Check only applies when accepting H₀ -~\n```\n\n\n:::\n:::\n\n\n**Note**: The HDI width check flagged a warning (0.0576 > 0.05 threshold). This indicates moderate precision—sufficient for rejecting H₀ (since HDI excludes ROPE), but we'd want narrower estimates if claiming equivalence. With N=50 subjects, the HDI width would likely pass this check.\n\n### Scenario Examples\n\n**Scenario 1: Wide HDI Inside ROPE**\n\n- 95% HDI: [0.01, 0.04] (width = 0.03, midpoint = 0.025)\n- ROPE: [-0.05, 0.05]\n- ✗ WRONG: \"Effect is negligible\"\n- ✓ RIGHT: \"HDI inside ROPE, but width suggests moderate uncertainty AND midpoint close to boundary. More data needed.\"\n\n**Scenario 2: Narrow HDI Centered Near Zero**\n\n- 95% HDI: [-0.005, 0.015] (width = 0.02, midpoint = 0.005)\n- ROPE: [-0.05, 0.05]\n- ✓ RIGHT: \"Effect is negligible. HDI is narrow, centered near zero, and falls well within ROPE.\"\n\n**Scenario 3: Narrow HDI But Off-Center**\n\n- 95% HDI: [0.03, 0.045] (width = 0.015, midpoint = 0.0375)\n- ROPE: [-0.05, 0.05]\n- ⚠ CAUTION: \"HDI is narrow and technically inside ROPE, but midpoint (0.0375) is close to upper boundary. Effect may be small but systematically positive. Consider whether this is practically negligible.\"\n\n**Scenario 4: HDI Overlaps ROPE Boundary**\n\n- 95% HDI: [0.03, 0.08]\n- ROPE: [-0.05, 0.05]\n- ✓ RIGHT: \"Undecided. Some credible values fall within ROPE, others exceed it. More data needed.\"\n\n::: {.callout-important}\n## Rules of Thumb for Precision\n\nBefore using ROPE to **accept H₀** (claim negligible effect), verify:\n\n**For RT effects (log-scale):**\n\n- HDI width < 0.05 log-units\n- HDI midpoint within ±0.025 of zero (inner 50% of typical ROPE)\n  - *Why?* If midpoint is near ROPE boundary, effect may be small but non-negligible.\n\n**For accuracy (probability scale):**\n\n- HDI width < 0.10\n- HDI midpoint within ±0.05 of zero\n\n**For all analyses:**\n\n- ESS (bulk) > 1000\n- ESS (tail) > 1000\n- Convergence diagnostics passed (R̂ < 1.01)\n\n**If these checks fail:**\n\n- Don't claim effect is negligible\n- Report \"insufficient precision\" or \"undecided\"\n- Consider collecting more data\n:::\n\n::: {.callout-tip}\n## When You Can Trust ROPE to Accept H₀\n\n**Strong evidence for negligible effect requires:**\n\n1. **Narrow posterior:** HDI width < half ROPE width\n2. **Central location:** HDI midpoint near zero\n3. **Good sampling:** ESS > 1000, R̂ < 1.01\n4. **Model fit:** Posterior predictive checks pass\n\n**Example of strong evidence:**\n```\nEffect: β = 0.02 (95% HDI: [0.01, 0.03])\nROPE: [-0.05, 0.05]\nHDI width: 0.02 (✓ narrow)\nESS: 2500 (✓ adequate)\n→ Can confidently claim negligible effect\n```\n\n**Example of weak evidence:**\n```\nEffect: β = 0.02 (95% HDI: [-0.01, 0.05])\nROPE: [-0.05, 0.05]\nHDI width: 0.06 (✗ too wide)\nESS: 800 (✗ marginal)\n→ Cannot confidently claim negligible effect\n```\n:::\n\n## Using bayestestR Package\n\nThe `bayestestR` package provides convenient functions for ROPE analysis.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` r\n# Proportion of samples inside the ROPE [-0.05, 0.05]:\n\nParameter  | Inside ROPE\n------------------------\nIntercept  |      0.00 %\nconditionB |      0.00 %\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nThe output shows:\n\n- **% in ROPE**: Proportion of 95% HDI inside ROPE\n- Interpretation automatically provided\n\n### Visualizing with bayestestR\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/bayestestr-plot-1.pdf)\n:::\n:::\n\n\n### Equivalence Test\n\nThe `equivalence_test()` function provides an integrated view:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` r\n# Test for Practical Equivalence\n\n  ROPE: [-0.05 0.05]\n\nParameter  |       H0 | inside ROPE |      95% HDI\n--------------------------------------------------\nIntercept  | Rejected |      0.00 % | [5.90, 6.05]\nconditionB | Rejected |      0.00 % | [0.08, 0.14]\n```\n\n\n:::\n:::\n\n\nThis shows for each parameter:\n\n- **% in ROPE**: How much of the posterior falls in ROPE\n- **Decision**: Accepted/Rejected/Undecided\n\n::: {.callout-note collapse=\"true\"}\n## Comparison: Manual vs bayestestR\n\nBoth approaches should give the same results:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` r\n# A tibble: 2 x 3\n  Source             `% in ROPE` Decision\n  <chr>                    <dbl> <chr>   \n1 Manual Calculation           0 Rejected\n2 bayestestR Package           0 Rejected\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## What Just Happened?\n\n**Both approaches give identical results** — bayestestR simply automates the manual calculations we did earlier. The benefit:\n- Less code to write\n- Automatic formatting\n- Built-in visualization\n- Consistent interface across analyses\n:::\n\n::: {.callout-tip}\n## When to Use Manual vs Package\n\n**Use manual calculation when:**\n\n- You want to understand the mechanics\n- You need custom ROPE boundaries for different parameters\n- You're teaching/explaining the concept\n\n**Use bayestestR when:**\n\n- You want quick, standardized results\n- You're analyzing many models\n- You want built-in visualization\n:::\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Prior Sensitivity Analysis for ROPE Decisions\n\n::: {.callout-important}\n## When Priors Matter\n\nFrom Kruschke (2015, Section 12.2.1): ROPE conclusions can change with different priors. **Always check sensitivity**, especially when:\n\n- Sample size is small (n < 30 per group)\n- HDI barely touches ROPE boundary\n- You're accepting H₀ (claiming negligible effect)\n:::\n\n### Demonstration: Same Data, Different Priors, Different ROPE Conclusions\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Prior   CI ROPE_low ROPE_high ROPE_Percentage\n1 Weakly Informative\\nN(0, 0.5) 0.95    -0.05      0.05      0.23894737\n2         Skeptical\\nN(0, 0.10) 0.95    -0.05      0.05      0.09894737\n3              Diffuse\\nN(0, 2) 0.95    -0.05      0.05      0.06157895\n   Decision\n1 Undecided\n2 Undecided\n3 Undecided\n```\n\n\n:::\n:::\n\n\n### Visualize Prior Sensitivity\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/prior-sensitivity-plot-1.pdf)\n:::\n:::\n\n\n### When ROPE Conclusions Hold vs. Change\n\n::: {.callout-tip}\n## ROPE Conclusions Hold When:\n\n✓ **Large sample size** (n > 30 per group)\n\n- Data overwhelms prior\n- Posterior similar regardless of prior choice\n\n✓ **Effect clearly outside or inside ROPE**\n\n- HDI far from ROPE boundaries\n- All reasonable priors give same conclusion\n\n✓ **Narrow posterior**\n\n- HDI width << ROPE width\n- High precision reduces prior influence\n\n\n:::\n\n::: {.callout-warning}\n## ROPE Conclusions Are Sensitive When:\n\n✗ **Small sample size** (n < 20 per group)\n- Prior has substantial influence\n- Different priors can change conclusion\n\n✗ **HDI barely touches ROPE boundary**\n- Effect ≈ 0.05 (right at threshold)\n- Small prior differences flip decision\n\n✗ **Wide posterior**\n- HDI width ≈ ROPE width\n- Uncertainty dominates\n\n**Example of sensitivity:**\n```\nData: N=15 subjects, effect ≈ 0.04 log-units\nROPE: [-0.05, 0.05]\nResult: \n  - Skeptical prior: 100% in ROPE (accept H₀)\n  - Diffuse prior: 60% in ROPE (undecided)\n→ Conclusion sensitive!\n```\n:::\n\n### What To Do If Conclusions Are Sensitive\n\n#### Option 1: Report Multiple Analyses (Recommended)\n\nReport all results from different prior specifications:\n\n#### Option 2: Justify Prior More Carefully\n\nIf conclusions are sensitive, invest more effort in prior justification:\n\n- Pilot data\n- Expert elicitation\n- Previous literature\n- Prior predictive checks (Module 02)\n\n**Report:** \"We used prior [X] because [justification]. Given potential sensitivity with small N, we verified conclusions hold with more diffuse prior.\"\n\n#### Option 3: Collect More Data\n\nIf:\n\n- Conclusions sensitive AND\n- You cannot justify prior AND  \n- Decision matters\n\n→ Collect more data before making decision\n\n::: {.callout-note}\n## This is NOT Optional Stopping / P-Hacking!\n\n**In NHST:** Looking at data, then deciding to collect more is a questionable research practice (QRP) - it inflates Type I error because your stopping rule affects the p-value.\n\n**In Bayesian analysis:** You CAN look at the data and decide to collect more without invalidating inference!\n\n**Why?** Bayesian inference follows the **likelihood principle**:\n\n- The posterior depends ONLY on the data and prior\n- NOT on your stopping intentions or whether you peeked\n- Looking at N=15, seeing inconclusive results, and collecting to N=60 gives the SAME posterior as pre-planning N=60\n\n**The difference:**\n\n- **NHST QRP**: \"Keep collecting until p < 0.05\" (invalidates test)\n- **Bayesian valid**: \"Keep collecting until HDI is narrow enough for confident decision\" (perfectly legitimate)\n\n**Caveat:** You still shouldn't change your ROPE boundaries or priors after seeing results!\n:::\n\n**Planning how much more data you need:**\n\nUse this power analysis to estimate target sample size for adequate precision:\n\n```r\n# Rule of thumb: HDI width inversely proportional to sqrt(n)\ncurrent_n <- 8        # Current sample size\ncurrent_hdi_width <- 0.10  # Current HDI width from preliminary analysis\ndesired_hdi_width <- 0.05  # Want HDI < half ROPE width for confident conclusions\n\n# Calculate target N needed\ntarget_n <- current_n * (current_hdi_width / desired_hdi_width)^2\n\ntibble(\n  Measure = c(\"Current N\", \"Current HDI width\", \"Desired HDI width\", \"Target N needed\", \"Additional N to collect\"),\n  Value = c(current_n, current_hdi_width, desired_hdi_width, round(target_n), round(target_n - current_n))\n)\n```\n\n**Interpretation:** To reduce HDI width from 0.10 to 0.05, you need to increase N by a factor of 4 (halving width requires quadrupling sample size).\n\n#### Option 4: Be Transparent About Uncertainty\n\nIf data collection isn't possible:\n\n```markdown\n\"Given our sample size (N=15), ROPE conclusions were sensitive to prior \nspecification. With weakly informative priors, X% of posterior fell in \nROPE, suggesting [interpretation]. With more skeptical priors, Y% fell \nin ROPE, suggesting [alternative interpretation]. We recommend treating \nthis finding as preliminary pending replication with larger sample.\"\n```\n\n### Worked Example: Prior Sensitivity Reporting\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 4\n  Prior                            Estimate `95% HDI`       `% in ROPE`\n  <chr>                               <dbl> <chr>                 <dbl>\n1 1. Weakly informative: N(0, 0.5)    0.037 [-0.307, 0.381]         0.2\n2 2. Skeptical: N(0, 0.10)            0.223 [-0.194, 0.597]         0.1\n3 3. Diffuse: N(0, 2)                 0.35  [-0.180, 0.850]         0.1\n```\n\n\n:::\n:::\n\n\n**Conclusion:** ROPE decision holds across prior specifications. All three priors yield: Undecided\n\n::: {.callout-note}\n## Main Point\n\n**Prior sensitivity is not a bug—it's a feature!**\n\nIt tells you when your data are:\n- **Strong enough** to overcome prior beliefs → Confident conclusions\n- **Too weak** to overcome prior beliefs (sensitive) → Need more data or transparency\n\nNHST doesn't have this diagnostic—it can give you \"p < 0.05\" even with barely any data, hiding the fact that different assumptions would give different answers.\n\nBayesian analysis makes sensitivity **explicit and quantifiable**.\n:::\n:::\n\n# Effect Estimation with emmeans\n\n::: {.callout-note}\n## Moving Beyond Single Comparisons\n\nSo far we've tested practical significance for a single effect (Condition B vs A). But what if you have **three or more groups**? You need:\n\n- All pairwise comparisons (A vs B, A vs C, B vs C)\n- ROPE analysis for each comparison\n- Adjustment for multiple comparisons (optional)\n\nThis is where **emmeans** and **marginaleffects** come in.\n:::\n\n## Why emmeans?\n\nWhen you have **factorial designs**, you often want to:\n\n- Compare all pairwise combinations\n- Estimate marginal means (averaged over random effects)\n- Get automatic adjustment for multiple comparisons\n- Use familiar syntax from frequentist stats\n\n**emmeans** (estimated marginal means) provides all of this and works directly with brms!\n\n## Example: Three-Condition Design\n\nLet's extend our example to three conditions:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 5\n  condition mean_rt sd_rt mean_log_rt sd_log_rt\n  <fct>       <dbl> <dbl>       <dbl>     <dbl>\n1 A            411.  78.8        6.00     0.193\n2 B            448.  99.7        6.08     0.221\n3 C            483. 102.         6.16     0.218\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Estimated Marginal Means\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **Estimated Marginal Means (Log RT)**\n\n|Condition |  Mean|        95% HDI|\n|:---------|-----:|--------------:|\n|A         | 6.001| [5.924, 6.073]|\n|B         | 6.081| [5.993, 6.167]|\n|C         | 6.161| [6.074, 6.241]|\n\n\n:::\n\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/emmeans-basic-1.pdf)\n:::\n:::\n\n\n::: {.callout-note}\n## What are \"Estimated Marginal Means\"?\n\nEMMs are model-predicted means that:\n\n- Average over random effects (subjects, items)\n- Provide population-level estimates\n- Include full Bayesian uncertainty (not just point estimates!)\n\nThink of them as \"What would we expect for a typical new subject/item?\"\n:::\n\n## Pairwise Comparisons\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **Pairwise Comparisons (Difference in Log RT)**\n\n|Contrast | Estimate|          95% HPD|\n|:--------|--------:|----------------:|\n|A - B    |   -0.080| [-0.113, -0.050]|\n|A - C    |   -0.158| [-0.216, -0.103]|\n|B - C    |   -0.077| [-0.139, -0.016]|\n\n\n:::\n\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/emmeans-pairwise-1.pdf)\n:::\n:::\n\n\n## ROPE Analysis on Pairwise Comparisons\n\nNow combine emmeans with ROPE to test practical significance of each comparison:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **ROPE Analysis Results for Pairwise Comparisons**\n\n|Comparison | Estimate|          95% HDI|Result                |\n|:----------|--------:|----------------:|:---------------------|\n|1          |   -0.080| [-0.113, -0.050]|↓ MEANINGFUL DECREASE |\n|2          |   -0.158| [-0.216, -0.103]|↓ MEANINGFUL DECREASE |\n|3          |   -0.077| [-0.139, -0.016]|? UNDECIDED           |\n\n\n:::\n\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/emmeans-rope-1.pdf)\n:::\n:::\n\n\n## Custom Contrasts\n\nemmeans allows custom contrasts beyond pairwise comparisons:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **Custom Contrasts**\n\n|Contrast | Estimate|        95% HDI|\n|:--------|--------:|--------------:|\n|BC_vs_A  |    0.119| [0.086, 0.153]|\n|C_vs_B   |    0.077| [0.016, 0.139]|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: **ROPE Analysis for Custom Contrasts**\n\n|Contrast |Decision                   |\n|:--------|:--------------------------|\n|1        |Meaningful positive effect |\n|2        |Undecided                  |\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Summary: emmeans\n\nYou should now understand:\n\n- Estimated marginal means (EMMs) are population-level predictions\n- `pairs()` gives all pairwise comparisons automatically\n- Extract posterior samples with `as.mcmc()` to integrate with ROPE\n- Works directly with brms for full Bayesian inference\n:::\n\n::: {.callout-tip}\n## When to Use emmeans\n\n**Perfect for:**\n\n- Factorial designs (2×2, 2×3, etc.)\n- All pairwise comparisons automatically\n- Familiar syntax from lsmeans/emmeans in frequentist stats\n- Integration with ROPE for practical significance\n\n**Not ideal for:**\n\n- Simple two-group comparisons (just use brms coefficients)\n- Complex non-linear predictions (use marginaleffects instead)\n- Interactions with continuous predictors (marginaleffects better)\n:::\n\n<details>\n<summary>**Effect Estimation with marginaleffects** (Under Construction - Click to Expand)</summary>\n\n::: {.callout-warning}\n## Section Under Development\n\nThis section is currently being revised and some tables/visualizations may not display correctly. The emmeans approach (above) is fully functional and recommended for now.\n:::\n\n# Effect Estimation with marginaleffects\n\n::: {.callout-note}\n## Modern Alternative to emmeans\n\nWhile emmeans is excellent for factorial designs, **marginaleffects** offers:\n\n- Unified syntax across ALL model types (not just brms)\n- More flexible predictions and comparisons\n- Better support for continuous predictors and interactions\n- Modern tidyverse-compatible workflow\n\nLet's see how it compares.\n:::\n\n## Why marginaleffects?\n\n**marginaleffects** provides a modern, unified interface for:\n\n- Predictions at specific values\n- Comparisons (differences, ratios, etc.)\n- Slopes (derivatives) for continuous predictors\n- Custom hypotheses with flexible syntax\n\nIt works with brms, rstanarm, glm, lme4, and many other models!\n\n## Visualize 95% Credible Intervals\n\n::: {.callout-note}\n## Two Approaches to Making Predictions\n\nmarginaleffects offers two main functions for predictions that differ in how they handle the dataset:\n\n### 1. predictions() with datagrid()\n\n```r\npredictions(rt_model_3, newdata = datagrid(condition = c(\"A\", \"B\", \"C\")))\n```\n\n- Creates a **single reference grid** with specified conditions\n- All other predictors held at their means/modes\n- Random effects set to 0 (population-level only)\n- Returns: \"What would we predict for a hypothetical average unit?\"\n\n### 2. avg_predictions()\n\n```r\navg_predictions(rt_model_3, variables = \"condition\")\n```\n\n- Makes predictions for **every observation** in the original dataset\n- Each prediction uses that observation's actual covariate values\n- Includes subject-specific random effects\n- Then **averages** these predictions across all observations\n- Returns: \"What is the average prediction across all units in our sample?\"\n\n**Which matches the data generation better?**\n\nOur data was generated with:\n\n- Baseline: 6.0\n- Condition B: 6.0 + random subject slopes (mean 0.10)\n- Condition C: 6.0 + random subject slopes (mean 0.18)\n\n`avg_predictions()` better captures this because:\n\n- It accounts for the empirical distribution of random subject intercepts and slopes\n- It averages over actual subjects in the data\n- True population means: A ≈ 6.0, B ≈ 6.1, C ≈ 6.18\n\n**How do these differ from emmeans?**\n\n| Aspect | avg_predictions() | emmeans() | predictions() + datagrid() |\n|--------|-------------------|-----------|---------------------------|\n| **Observations used** | All rows in original data | All rows in original data | Single reference grid |\n| **Random effects** | Actual fitted values per subject | Integrated over distribution | Set to 0 |\n| **Interpretation** | \"Average of predictions\" | \"Estimated marginal mean\" | \"Conditional prediction at reference\" |\n| **Best for** | Descriptive summaries | Population-level inference | Scenario analysis |\n\n`avg_predictions()` and `emmeans()` should give **similar results** because both average over the actual data, but may differ slightly in:\n\n- Computational method (averaging vs. marginalization)\n- Treatment of random effects in the averaging process\n- Default settings for transforms and scales\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **Average Predicted vs. Observed Log RT by Condition**\n\n|Condition | Observed Mean| Model Prediction| Difference|         95% CI|\n|:---------|-------------:|----------------:|----------:|--------------:|\n|A         |         5.999|            5.999|      0.000| [5.993, 6.006]|\n|B         |         6.080|            6.080|      0.000| [6.074, 6.086]|\n|C         |         6.157|            6.157|      0.000| [6.151, 6.163]|\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Model Fit Check\n\nThe table above shows how well the model predictions match the actual observed means in the data. \n\n**True data generation parameters:**\n\n- A: 6.00 (baseline)\n- B: 6.10 (baseline + 0.10)\n- C: 6.18 (baseline + 0.18)\n\nThe small differences between observed means and model predictions are due to:\n\n1. **Random sampling variation** in data generation (random effects and residuals)\n2. **Shrinkage from Bayesian priors** pulling estimates toward more conservative values\n3. **Regularization** from the hierarchical structure preventing overfitting to sample means\n\nThis is working as intended! The model balances fitting the data with reasonable prior constraints.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/margeff-predictions-viz-1.pdf)\n:::\n:::\n\n\n## Raw Posterior Draws\n\n::: {.callout-note}\n## Approach: Posterior Distribution Visualization\n\nThis section extracts the **full posterior distributions** from pairwise comparisons using `posterior_draws()`. This allows us to:\n\n1. Visualize the complete uncertainty in each comparison\n2. Add ROPE boundaries to assess practical significance\n3. Calculate custom summary statistics (mean, HDI) from the raw posterior samples\n\n**Why this approach?** When you need to visualize distributions, check overlap with ROPE, or compute custom summaries beyond what marginaleffects provides by default.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/margeff-comparisons-1.pdf)\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **Pairwise Comparison Estimates**\n\n|Comparison | Estimate|         95% HDI|\n|:----------|--------:|---------------:|\n|B vs A     |    0.081| [-0.045, 0.252]|\n|C vs A     |    0.158| [-0.064, 0.442]|\n|C vs B     |    0.077| [-0.246, 0.389]|\n\n\n:::\n:::\n\n\n## Using marginaleffects Summary Statistics (better)\n\n::: {.callout-note}\n## Approach: Summary Statistics from marginaleffects\n\nThis section uses marginaleffects' **built-in summary statistics** directly from the comparison objects. This approach:\n\n1. Uses pre-computed estimates and credible intervals from marginaleffects\n2. Shows the \"average\" comparison across the dataset\n3. Is more efficient when you only need point estimates and CIs\n\n**Why do estimates differ from Section 5.3?**\n\nThe differences arise from **how posterior draws are summarized**:\n\n### Section 5.3: Manual Posterior Summarization\n\nWhen we use `posterior_draws()` and then manually compute `mean(draw)`:\n\n```r\nposterior_draws(comp_B_vs_A) |> \n  summarise(Estimate = mean(draw))\n```\n\nThis computes: **mean of all posterior draws from the comparison distribution**\n\n- Each posterior draw represents: β_B - β_A from a single MCMC iteration\n- We're averaging across all 4000 posterior samples\n- This gives us the expected value of the comparison\n\n### Section 5.4: marginaleffects Default Summary\n\nWhen we use `comp_B_vs_A` directly:\n\n```r\ncomp_B_vs_A %>% as.data.frame() %>% select(estimate)\n```\n\nmarginaleffects computes the comparison **at each unit in newdata** first, then summarizes:\n\n1. For each posterior draw: Make predictions at all covariate values\n2. For each posterior draw: Compute comparison (B - A) at each covariate value  \n3. Average across units (if multiple rows in newdata)\n4. Then summarize across posterior draws\n\n**Key difference:** marginaleffects averages **within** each posterior draw before summarizing across draws. This is especially important with:\n\n- **Non-linear models** (like logistic regression): Predictions depend on covariate values\n- **Interactions**: Effect of condition may differ by subject characteristics\n- **Random effects**: Unit-level predictions include random effect realizations\n\n### Comparison Direction\n\nBoth sections compute **B - A**, **C - A**, and **C - B** (second condition minus first):\n\n```r\ncomparisons(rt_model_3, variables = list(condition = c(\"A\", \"B\")))\n# Compares: B vs A (i.e., B - A)\n```\n\nThe order in `list(condition = c(\"A\", \"B\"))` matters: the second element is compared to the first.\n\n### When Do They Match?\n\nThe two approaches give **identical** results when:\n\n- Linear model with no interactions\n- All observations have identical covariate values\n- No random effects (population-level only)\n\nIn mixed-effects models with random effects and subject-level covariates, the differences can be substantial because:\n\n- Section 5.3: Averages raw posterior samples from the comparison distribution\n- Section 5.4: Averages predictions across the **empirical distribution** of covariates in your data, then summarizes\n\n### Which Should You Use?\n\n- **Section 5.3 (posterior_draws)**: When you want to visualize full distributions, check ROPE overlap, or compute custom summaries\n- **Section 5.4 (direct comparison)**: When you want marginaleffects' default averaging method, which accounts for the distribution of covariates in your sample\n\nFor most mixed-effects models, **Section 5.4's approach** is preferred because it properly accounts for the empirical distribution of random effects and covariates.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **All Pairwise Comparisons**\n\n|Comparison | Difference|          95% CI|\n|:----------|----------:|---------------:|\n|B vs A     |     -0.021| [-0.068, 0.026]|\n|C vs A     |      0.033| [-0.014, 0.080]|\n|C vs B     |      0.054|  [0.007, 0.102]|\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Why No Visualization Here?\n\nUnlike Section 5.3, we **don't show a three-panel graph** here because:\n\n1. **The table shows marginaleffects summary statistics** (estimates averaged across the empirical distribution)\n2. **Using `posterior_draws()` would show the same distributions as Section 5.3** (defeating the purpose of comparing approaches)\n3. **The key difference is in the summary method, not the posterior distributions themselves**\n\nIf we visualized `posterior_draws(comp_B_vs_A)` here, it would be **identical to Section 5.3** because both extract the same raw MCMC samples. The difference between sections 5.3 and 5.4 is:\n\n- **Section 5.3**: Manually extracts posterior draws and computes `mean(draw)` → gives one type of summary\n- **Section 5.4**: Uses marginaleffects' internal averaging over observations → gives a different summary\n\nThe **posterior distributions are the same**; only the **summarization differs**. The table above shows marginaleffects' summary, which accounts for averaging predictions across all covariate values in the dataset before summarizing across posterior draws.\n\nTo visualize the marginaleffects approach properly, you would need to show prediction distributions at individual covariate values, then average them—which is complex and not typically done. The table is the appropriate summary for this approach.\n:::\n\n**However**, we can visualize how the **summary statistics differ** between the two approaches:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/compare-approaches-viz-1.pdf)\n:::\n:::\n\n\nThis visualization shows why the two approaches give different estimates:\n\n- **Orange (Section 5.3)**: Posterior draws approach—computes `mean(posterior_draws)`\n- **Blue (Section 5.4)**: marginaleffects summary—averages predictions at unit level before summarizing\n\nThe key insight: both methods use the **same posterior samples**, but summarize them differently. Section 5.3's approach tends to give larger estimates because it doesn't average over the empirical distribution of covariates and random effects in the same way.\n\n\n## Custom Comparisons Example\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: **Custom Comparison: C vs Average(A, B)**\n\n|Measure      |          Value|\n|:------------|--------------:|\n|Estimate     |          0.044|\n|95% HDI      | [0.003, 0.085]|\n|% Below ROPE |           0.0%|\n|% In ROPE    |          61.1%|\n|% Above ROPE |          38.9%|\n\n\n:::\n\n::: {.cell-output-display}\n![](06_rope_files/figure-pdf/margeff-custom-comparison-1.pdf)\n:::\n:::\n\n\n### Decision\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|                             |\n|:----------------------------|\n|⚠ Undecided - need more data |\n\n\n:::\n:::\n\n\n</details>\n\n# ROPE Reporting\n\n::: {.callout-important}\n## What to Always Report\n\nFrom Kruschke (2015, p. 338):\n\n> \"Reporting the limits of an HDI region is more informative than reporting the declaration of a reject/accept decision. By reporting the HDI and other summary information about the posterior, different readers can apply different ROPEs to decide for themselves whether a parameter is practically equivalent to a null value.\"\n\n**Complete reporting includes:**\n\n1. Full posterior summary (not just inside/outside ROPE)\n2. ROPE boundaries with justification\n3. Effect size on multiple scales\n4. Model diagnostics\n5. Sensitivity checks\n:::\n\n### Methods Section Template\n\n\n::: {.cell}\n\n:::\n\n\n**Include in Methods:**\n\n- Prior specification with rationale\n- ROPE boundaries with justification\n- When boundaries were set (a priori)\n- How boundaries relate to original scale\n- Sample size (subjects, items, observations)\n- Software versions\n\n### Results Section Template\n\n\n::: {.cell}\n\n:::\n\n\n**Include in Results:**\n\n- Point estimate with HDI (on model scale)\n- Posterior SD or uncertainty measure\n- % of posterior in/outside ROPE\n- Decision statement (reject/accept/undecided H₀)\n- Effect size on original scale with interpretation\n- Absolute magnitudes (e.g., milliseconds) where relevant\n- Robustness checks (prior sensitivity, model comparison)\n\n\n\n\n\n\n# When to Use What: Decision Framework\n\n\n::: {.callout-tip}\n## Quick Decision Tree\n\n**What do you want to test?**\n\n→ \"Is the effect big enough to matter?\" → Use ROPE  \n→ \"Which hypothesis is better supported?\" → See Module 07 (Bayes Factors)  \n→ \"Which model fits better?\" → Use LOO (Module 03)\n\n:::\n\n## Visual Guide: Choosing Your Tools\n\n```\nYour Research Question\n  │\n  ├─→ \"Is effect meaningful?\" ────────────→ ROPE\n  │\n  ├─→ \"Compare 3+ groups?\" \n  │     ├─→ Factorial design ────────────→ emmeans + ROPE\n  │     └─→ Custom predictions ──────────→ marginaleffects + ROPE\n  │\n  ├─→ \"Which hypothesis better?\" ────────→ Module 07 (Bayes Factors)\n  │\n  └─→ \"Which model structure?\" ──────────→ Module 05 (LOO)\n```\n\n\n# Avoiding Pitfalls: Checklist\n\nBefore running analyses:\n\n- Priors are **weakly informative** (not flat)?  \n- ROPE boundaries defined **before** seeing results?\n- ROPE boundaries **justified** with domain knowledge?\n- Hypotheses based on **theory**, not data exploration?\n\nWhen interpreting results:\n\n- Report **ROPE decision** and effect sizes?\n- Report **uncertainty** (don't hide ROPE overlaps)?\n- Check **prior sensitivity** (Module 04)?\n- Show **posterior distributions visually**?\n- Interpret on the **original scale** when possible?\n\n# Quick Reference\n\n**Main papers:**\n\n- **Kruschke, J. K. (2018).** Rejecting or accepting parameter values in Bayesian estimation. *Advances in Methods and Practices in Psychological Science*, 1(2), 270-280. [The definitive ROPE paper]\n- **Kruschke, J. K. (2015).** *Doing Bayesian data analysis* (2nd ed.). Academic Press. [Chapters 11-12]\n- **Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., & Rubin, D. B. (2013).** *Bayesian data analysis* (3rd ed.). CRC Press. [Chapter 9: Decision Analysis]\n- **Vehtari, A., Gelman, A., Simpson, D., Carpenter, B., & Bürkner, P.-C. (2021).** Rank-normalization, folding, and localization: An improved R̂ for assessing convergence of MCMC (with discussion). *Bayesian Analysis*, 16(2), 667-718. [ESS diagnostics]\n- **Makowski, D., Ben-Shachar, M. S., & Lüdecke, D. (2019).** bayestestR: Describing effects and their uncertainty. *Journal of Open Source Software*, 4(40), 1541.\n- **Lakens, D., Scheel, A. M., & Isager, P. M. (2018).** Equivalence testing for psychological research. *Advances in Methods and Practices in Psychological Science*, 1(2), 259-269.\n\n## Session Info\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31)\nPlatform: x86_64-pc-linux-gnu\nRunning under: Ubuntu 24.04.3 LTS\n\nMatrix products: default\nBLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 \nLAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Etc/UTC\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] knitr_1.51             patchwork_1.3.2        marginaleffects_0.31.0\n [4] emmeans_2.0.1          bayestestR_0.17.0      tidybayes_3.0.7       \n [7] posterior_1.6.1.9000   bayesplot_1.15.0       lubridate_1.9.4       \n[10] forcats_1.0.1          stringr_1.5.2          dplyr_1.1.4           \n[13] purrr_1.1.0            readr_2.1.5            tidyr_1.3.2           \n[16] tibble_3.3.0           ggplot2_4.0.1          tidyverse_2.0.0       \n[19] brms_2.23.0            Rcpp_1.1.0            \n\nloaded via a namespace (and not attached):\n [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n [4] loo_2.9.0             S7_0.2.0              fastmap_1.2.0        \n [7] tensorA_0.36.2.1      digest_0.6.37         timechange_0.3.0     \n[10] estimability_1.5.1    lifecycle_1.0.4       StanHeaders_2.32.10  \n[13] processx_3.8.6        magrittr_2.0.4        compiler_4.5.2       \n[16] rlang_1.1.6           tools_4.5.2           utf8_1.2.6           \n[19] yaml_2.3.10           collapse_2.1.5        data.table_1.17.8    \n[22] labeling_0.4.3        bridgesampling_1.2-1  pkgbuild_1.4.8       \n[25] plyr_1.8.9            RColorBrewer_1.1-3    cmdstanr_0.9.0       \n[28] abind_1.4-8           withr_3.0.2           datawizard_1.3.0     \n[31] grid_4.5.2            stats4_4.5.2          xtable_1.8-4         \n[34] inline_0.3.21         ggridges_0.5.7        scales_1.4.0         \n[37] tinytex_0.57          insight_1.4.4         cli_3.6.5            \n[40] mvtnorm_1.3-3         rmarkdown_2.30        generics_0.1.4       \n[43] otel_0.2.0            RcppParallel_5.1.11-1 reshape2_1.4.5       \n[46] tzdb_0.5.0            rstan_2.32.7          HDInterval_0.2.4     \n[49] parallel_4.5.2        matrixStats_1.5.0     vctrs_0.6.5          \n[52] Matrix_1.7-4          jsonlite_2.0.0        hms_1.1.4            \n[55] arrayhelpers_1.1-0    ggdist_3.3.3          see_0.12.0           \n[58] glue_1.8.0            codetools_0.2-20      ps_1.9.1             \n[61] distributional_0.5.0  stringi_1.8.7         gtable_0.3.6         \n[64] QuickJSR_1.8.1        pillar_1.11.1         htmltools_0.5.8.1    \n[67] Brobdingnag_1.2-9     R6_2.6.1              evaluate_1.0.5       \n[70] lattice_0.22-7        backports_1.5.0       rstantools_2.5.0     \n[73] coda_0.19-4.1         gridExtra_2.3         nlme_3.1-168         \n[76] checkmate_2.3.3       xfun_0.55             pkgconfig_2.0.3      \n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}